buildpacks:
- name: binary_buildpack
  repo_name: binary-buildpack
  stack: cflinuxfs3
  version: v1.0.36
  sha: 8bf473f805b9e8deff6f58d57533737d6afe02fa3ad6a27073e73e100b2b0937
  filename: binary-buildpack-cflinuxfs3-v1.0.36.zip
  url: https://github.com/cloudfoundry/binary-buildpack/releases/download/v1.0.36/binary-buildpack-cflinuxfs3-v1.0.36.zip
  dependencies: []
- name: dotnet_core_buildpack
  repo_name: dotnet-core-buildpack
  stack: cflinuxfs3
  version: v2.3.14
  sha: c96742e8ed55ae60c722fde43bb99455d85181c9fc4e4887da725a42e6149c4a
  filename: dotnet-core-buildpack-cflinuxfs3-v2.3.14.zip
  url: https://github.com/cloudfoundry/dotnet-core-buildpack/releases/download/v2.3.14/dotnet-core-buildpack-cflinuxfs3-v2.3.14.zip
  dependencies:
  - name: bower
    version: 1.8.8
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-aspnetcore
    version: 2.1.20
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-aspnetcore
    version: 2.1.21
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-aspnetcore
    version: 3.1.6
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-aspnetcore
    version: 3.1.7
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-runtime
    version: 2.1.20
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-runtime
    version: 2.1.21
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-runtime
    version: 3.1.6
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-runtime
    version: 3.1.7
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-sdk
    version: 2.1.808
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-sdk
    version: 2.1.809
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-sdk
    version: 3.1.302
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-sdk
    version: 3.1.401
    cf_stacks:
    - cflinuxfs3
  - name: libgdiplus
    version: "6.0"
    cf_stacks:
    - cflinuxfs3
  - name: libunwind
    version: 1.4.0
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 10.22.0
    cf_stacks:
    - cflinuxfs3
- name: go_buildpack
  repo_name: go-buildpack
  stack: cflinuxfs3
  version: v1.9.17
  sha: 8c8af2169e038fa51b5bfb86f6fbce61ad48dd938d2a7fd89c6748164cf9621b
  filename: go-buildpack-cflinuxfs3-v1.9.17.zip
  url: https://github.com/cloudfoundry/go-buildpack/releases/download/v1.9.17/go-buildpack-cflinuxfs3-v1.9.17.zip
  dependencies:
  - name: dep
    version: 0.5.4
    cf_stacks:
    - cflinuxfs3
  - name: glide
    version: 0.13.3
    cf_stacks:
    - cflinuxfs3
  - name: go
    version: 1.13.14
    cf_stacks:
    - cflinuxfs3
  - name: go
    version: 1.13.15
    cf_stacks:
    - cflinuxfs3
  - name: go
    version: 1.14.6
    cf_stacks:
    - cflinuxfs3
  - name: go
    version: 1.14.7
    cf_stacks:
    - cflinuxfs3
  - name: go
    version: "1.15"
    cf_stacks:
    - cflinuxfs3
  - name: godep
    version: "80"
    cf_stacks:
    - cflinuxfs3
- name: java_buildpack
  repo_name: java-buildpack
  stack: cflinuxfs3
  version: v4.32.1
  sha: 3376918240b8b9f16f9b51e6dcec946f1f495a8ccd2209de9ab71e82d3a8760c
  filename: java-buildpack-v4.32.1.zip
  url: https://github.com/cloudfoundry/java-buildpack/releases/download/v4.32.1/java-buildpack-v4.32.1.zip
  dependencies: []
- name: nodejs_buildpack
  repo_name: nodejs-buildpack
  stack: cflinuxfs3
  version: v1.7.26
  sha: 60134fb3d94dac38ae9c8bacb61a4396b0a3bc25108fbd61ce6b71cd112564e3
  filename: nodejs-buildpack-cflinuxfs3-v1.7.26.zip
  url: https://github.com/cloudfoundry/nodejs-buildpack/releases/download/v1.7.26/nodejs-buildpack-cflinuxfs3-v1.7.26.zip
  dependencies:
  - name: node
    version: 10.21.0
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 10.22.0
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 12.18.2
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 12.18.3
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 14.7.0
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 14.8.0
    cf_stacks:
    - cflinuxfs3
  - name: yarn
    version: 1.22.4
    cf_stacks:
    - cflinuxfs3
- name: php_buildpack
  repo_name: php-buildpack
  stack: cflinuxfs3
  version: v4.4.20
  sha: 666ffccbe71c4a2d30fe484ff9945fa8e6a7d42088d5a19fb4262c4811e548f7
  filename: php-buildpack-cflinuxfs3-v4.4.20.zip
  url: https://github.com/cloudfoundry/php-buildpack/releases/download/v4.4.20/php-buildpack-cflinuxfs3-v4.4.20.zip
  dependencies:
  - name: CAAPM
    version: 20.1.0
    cf_stacks:
    - cflinuxfs3
  - name: appdynamics
    version: 20.4.0.3759
    cf_stacks:
    - cflinuxfs3
  - name: composer
    version: 1.10.10
    cf_stacks:
    - cflinuxfs3
  - name: httpd
    version: 2.4.46
    cf_stacks:
    - cflinuxfs3
  - name: newrelic
    version: 9.1.0.246
    cf_stacks:
    - cflinuxfs3
  - name: nginx
    version: 1.18.0
    cf_stacks:
    - cflinuxfs3
  - name: nginx
    version: 1.19.2
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 7.2.32
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 7.2.33
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 7.3.20
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 7.3.21
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 7.4.8
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 7.4.9
    cf_stacks:
    - cflinuxfs3
- name: python_buildpack
  repo_name: python-buildpack
  stack: cflinuxfs3
  version: v1.7.19
  sha: 3f53398108b2e9c4d5aa39b881c8e745ef7e0fd8ddfb2793d999596aa39c6561
  filename: python-buildpack-cflinuxfs3-v1.7.19.zip
  url: https://github.com/cloudfoundry/python-buildpack/releases/download/v1.7.19/python-buildpack-cflinuxfs3-v1.7.19.zip
  dependencies:
  - name: libffi
    version: 3.2.1
    cf_stacks:
    - cflinuxfs3
  - name: libmemcache
    version: 1.0.18
    cf_stacks:
    - cflinuxfs3
  - name: miniconda3
    version: 4.7.12.1
    cf_stacks:
    - cflinuxfs3
  - name: pip-pop
    version: 0.1.5
    cf_stacks:
    - cflinuxfs3
  - name: pipenv
    version: 2020.8.13
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.5.7
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.5.9
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.6.10
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.6.11
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.7.7
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.7.8
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.8.3
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.8.5
    cf_stacks:
    - cflinuxfs3
  - name: setuptools
    version: 49.6.0
    cf_stacks:
    - cflinuxfs3
- name: ruby_buildpack
  repo_name: ruby-buildpack
  stack: cflinuxfs3
  version: v1.8.23
  sha: 391982d7d75df588120ac7cf2dd7db95a81e0d6c46e5998c43eb9c8f51fd842c
  filename: ruby-buildpack-cflinuxfs3-v1.8.23.zip
  url: https://github.com/cloudfoundry/ruby-buildpack/releases/download/v1.8.23/ruby-buildpack-cflinuxfs3-v1.8.23.zip
  dependencies:
  - name: bundler
    version: 1.17.3
    cf_stacks:
    - cflinuxfs3
  - name: bundler
    version: 2.1.4
    cf_stacks:
    - cflinuxfs3
  - name: jruby
    version: 9.1.17.0
    cf_stacks:
    - cflinuxfs3
  - name: jruby
    version: 9.2.13.0
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 10.22.0
    cf_stacks:
    - cflinuxfs3
  - name: openjdk1.8-latest
    version: 1.8.0
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 2.5.7
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 2.5.8
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 2.6.5
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 2.6.6
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 2.7.0
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 2.7.1
    cf_stacks:
    - cflinuxfs3
  - name: rubygems
    version: 3.1.4
    cf_stacks:
    - cflinuxfs3
  - name: yarn
    version: 1.22.4
    cf_stacks:
    - cflinuxfs3
- name: staticfile_buildpack
  repo_name: staticfile-buildpack
  stack: cflinuxfs3
  version: v1.5.10
  sha: cb1dce2f5079417f4d424e5e08930d9a56a89c62fdc85b98c8fa051f6a310083
  filename: staticfile-buildpack-cflinuxfs3-v1.5.10.zip
  url: https://github.com/cloudfoundry/staticfile-buildpack/releases/download/v1.5.10/staticfile-buildpack-cflinuxfs3-v1.5.10.zip
  dependencies:
  - name: nginx
    version: 1.19.2
    cf_stacks:
    - cflinuxfs3
- name: nginx_buildpack
  repo_name: nginx-buildpack
  stack: cflinuxfs3
  version: v1.1.14
  sha: 3999db4dda61394994205b98f9298dea05c31e533fe696407ff2db0c4a1bd679
  filename: nginx-buildpack-cflinuxfs3-v1.1.14.zip
  url: https://github.com/cloudfoundry/nginx-buildpack/releases/download/v1.1.14/nginx-buildpack-cflinuxfs3-v1.1.14.zip
  dependencies:
  - name: nginx
    version: 1.18.0
    cf_stacks:
    - cflinuxfs3
  - name: nginx
    version: 1.19.2
    cf_stacks:
    - cflinuxfs3
  - name: openresty
    version: 1.13.6.2
    cf_stacks:
    - cflinuxfs3
  - name: openresty
    version: 1.15.8.3
    cf_stacks:
    - cflinuxfs3
  - name: openresty
    version: 1.17.8.1
    cf_stacks:
    - cflinuxfs3
- name: r_buildpack
  repo_name: r-buildpack
  stack: cflinuxfs3
  version: v1.1.7
  sha: 8402ff90725b463e4f444de897188c260eeb2dd031b895a2979fb496ac971ed8
  filename: r-buildpack-cflinuxfs3-v1.1.7.zip
  url: https://github.com/cloudfoundry/r-buildpack/releases/download/v1.1.7/r-buildpack-cflinuxfs3-v1.1.7.zip
  dependencies:
  - name: r
    version: 3.5.2
    cf_stacks:
    - cflinuxfs3
  - name: r
    version: 3.5.3
    cf_stacks:
    - cflinuxfs3
  - name: r
    version: 3.6.2
    cf_stacks:
    - cflinuxfs3
  - name: r
    version: 3.6.3
    cf_stacks:
    - cflinuxfs3
  - name: r
    version: 4.0.1
    cf_stacks:
    - cflinuxfs3
  - name: r
    version: 4.0.2
    cf_stacks:
    - cflinuxfs3
