---
- type: replace
  path: /instance_groups/name=credhub/jobs/name=credhub/properties/credhub/data_storage
  value:
    database: credhub
    host: "((terraform_outputs_cf_db_address))"
    password: "((external_credhub_database_password))"
    port: 5432
    type: postgres
    username: credhub
    tls_ca: "((aws_rds_combined_ca_bundle))"

- type: replace
  path: /instance_groups/name=credhub/vm_extensions?/-
  value: cf_rds_client_sg

- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/consumes?
  value:
    credhub:
      from: credhub
      deployment: ((deployment_name))

- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/uaa/clients/cc_service_key_client?
  value:
    authorities: credhub.read,credhub.write
    authorized-grant-types: client_credentials
    override: true
    secret: ((uaa_clients_cc_service_key_client_secret))

- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/uaa/clients/credhub_admin_client?
  value:
    authorities: credhub.read,credhub.write
    authorized-grant-types: client_credentials
    override: true
    secret: ((credhub_admin_client_secret))

- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/credhub_api?
  value:
    hostname: credhub.service.cf.internal
    ca_cert: ((credhub_tls.ca))

# FIXME: Reduce the power of this rule before going to production
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/security_group_definitions/-
  value:
    name: access_to_credhub
    rules:
      - protocol: tcp
        destination: 10.0.0.0/8
        ports: '8844'

- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/default_running_security_groups/-
  value: access_to_credhub

- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/default_staging_security_groups/-
  value: access_to_credhub
