---
- type: replace
  path: /releases/-
  value:
    name: vcap-services-interpolator
    version: 0.1.1
    url: https://s3-eu-west-1.amazonaws.com/gds-paas-build-releases/vcap-services-interpolator-0.1.1.tgz
    sha1: 7055202b25282805e11c97bfd574a34bbb7b6a5c

- type: replace
  path: /instance_groups/name=api/jobs?/-
  value:
    name: vcap-services-interpolator
    release: vcap-services-interpolator
    properties:
      port: 8844
      tls:
        server_cert: ((vcap_services_interpolator_server_cert.certificate))
        server_key: ((vcap_services_interpolator_server_cert.private_key))
        instance_identity_ca: ((diego_instance_identity_ca.certificate))
      # These properties are just there for the release to re-export as the
      # "credhub" link provided below. See the job's spec file for more.
      credhub:
        port: 8844
        ca_certificate: ((vcap_services_interpolator_server_cert.ca))
        internal_url: vcap-services-interpolator.service.cf.internal
    provides:
      credhub:
        as: vcap_services_credhub
        shared: true

# Have Cloud Controller use vcap-services-interpolator as CredHub, and
# it will then have app lifecycles do the same
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/credhub_api?
  value:
    hostname: vcap-services-interpolator.service.cf.internal
    ca_cert: ((vcap_services_interpolator_server_cert.ca))

- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/consumes?
  value:
    credhub:
      from: vcap_services_credhub
      deployment: ((deployment_name))

# Add a certificate and DNS entry
- type: replace
  path: /variables/-
  value:
    name: vcap_services_interpolator_server_cert
    options:
      ca: service_cf_internal_ca
      common_name: vcap-services-interpolator.service.cf.internal
      extended_key_usage:
      - server_auth
    type: certificate

- type: replace
  path: /addons/name=bosh-dns-aliases/jobs/name=bosh-dns-aliases/properties/aliases/-
  value:
    domain: vcap-services-interpolator.service.cf.internal
    targets:
    - query: '*'
      instance_group: api
      deployment: ((deployment_name))
      network: ((network_name))
      domain: bosh

# Make apps (and app lifecycles) trust the certificate
- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=cflinuxfs3-rootfs-setup/properties/cflinuxfs3-rootfs/trusted_certs/-
  value: ((vcap_services_interpolator_server_cert.ca))

- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=rep/properties/containers/trusted_ca_certificates/-
  value: ((vcap_services_interpolator_server_cert.ca))

# FIXME: I suspect this isn't needed
- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=rep/properties/containers/proxy/trusted_ca_certificates/-
  value: ((vcap_services_interpolator_server_cert.ca))

# Give apps (and app lifecycles) network access to the vcap-services-interpolator
# FIXME: Reduce the power of this rule before going to production
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/security_group_definitions/-
  value:
    name: access_to_vcap_services_interpolator
    rules:
      - protocol: tcp
        destination: 10.0.0.0/8
        ports: '8844'

- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/default_running_security_groups/-
  value: access_to_vcap_services_interpolator

- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/default_staging_security_groups/-
  value: access_to_vcap_services_interpolator
